export const LOAD_ALBUMS_SUCCESS = "LOAD_ALBUMS_SUCCESS";
export const VIEW_ALBUM = "VIEW_ALBUM";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR"; 
export const VIEW_FAVORITES_SUCCESS = "VIEW_FAVORITES_SUCCESS";
export const SAVE_TO_FAVORITES_SUCCESS = "SAVE_TO_FAVORITES_SUCCESS";
export const SAVE_TO_FAVORITES = "SAVE_TO_FAVORITES";